# Generated by Django 2.2.16 on 2020-11-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0004_create_default_permissions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='interface',
            field=models.CharField(default='', max_length=64),
        ),
    ]
