# Generated by Django 2.2.16 on 2020-11-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0005_uploader_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=36, unique=True)),
                ('dfo_id', models.IntegerField()),
                ('offset', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('instrument_id', models.IntegerField(null=True))
            ],
            options={
                'ordering': ['offset'],
                'unique_together': {('dfo_id', 'offset')},
            },
        ),
    ]
